
#include "hplmxp.hpp"

template <>
void HPLMXP_gemmNT(const int     m,
                   const int     n,
                   const int     k,
                   const double  alpha,
                   const double* a,
                   const int     lda,
                   const double* b,
                   const int     ldb,
                   const double  beta,
                   double*       c,
                   const int     ldc) {
  ROCBLAS_CHECK(rocblas_gemm_ex(blas_hdl,
                                rocblas_operation_none,
                                rocblas_operation_transpose,
                                m,
                                n,
                                k,
                                &alpha,
                                a,
                                rocblas_datatype_f64_r,
                                lda,
                                b,
                                rocblas_datatype_f64_r,
                                ldb,
                                &beta,
                                c,
                                rocblas_datatype_f64_r,
                                ldc,
                                c,
                                rocblas_datatype_f64_r,
                                ldc,
                                rocblas_datatype_f64_r,
                                rocblas_gemm_algo_standard,
                                0,
                                rocblas_gemm_flags_none));
}

template <>
void HPLMXP_gemmNT(const int    m,
                   const int    n,
                   const int    k,
                   const float  alpha,
                   const float* a,
                   const int    lda,
                   const float* b,
                   const int    ldb,
                   const float  beta,
                   float*       c,
                   const int    ldc) {
  ROCBLAS_CHECK(rocblas_gemm_ex(blas_hdl,
                                rocblas_operation_none,
                                rocblas_operation_transpose,
                                m,
                                n,
                                k,
                                &alpha,
                                a,
                                rocblas_datatype_f32_r,
                                lda,
                                b,
                                rocblas_datatype_f32_r,
                                ldb,
                                &beta,
                                c,
                                rocblas_datatype_f32_r,
                                ldc,
                                c,
                                rocblas_datatype_f32_r,
                                ldc,
                                rocblas_datatype_f32_r,
                                rocblas_gemm_algo_standard,
                                0,
                                rocblas_gemm_flags_none));
}

template <>
void HPLMXP_gemmNT(const int     m,
                   const int     n,
                   const int     k,
                   const float   alpha,
                   const __half* a,
                   const int     lda,
                   const __half* b,
                   const int     ldb,
                   const float   beta,
                   float*        c,
                   const int     ldc) {
  ROCBLAS_CHECK(rocblas_gemm_ex(blas_hdl,
                                rocblas_operation_none,
                                rocblas_operation_transpose,
                                m,
                                n,
                                k,
                                &alpha,
                                a,
                                rocblas_datatype_f16_r,
                                lda,
                                b,
                                rocblas_datatype_f16_r,
                                ldb,
                                &beta,
                                c,
                                rocblas_datatype_f32_r,
                                ldc,
                                c,
                                rocblas_datatype_f32_r,
                                ldc,
                                rocblas_datatype_f32_r,
                                rocblas_gemm_algo_standard,
                                0,
                                rocblas_gemm_flags_none));
}

template <>
void HPLMXP_gemmNT(const int     m,
                   const int     n,
                   const int     k,
                   const __half  alpha,
                   const __half* a,
                   const int     lda,
                   const __half* b,
                   const int     ldb,
                   const __half  beta,
                   __half*       c,
                   const int     ldc) {
  ROCBLAS_CHECK(rocblas_gemm_ex(blas_hdl,
                                rocblas_operation_none,
                                rocblas_operation_transpose,
                                m,
                                n,
                                k,
                                &alpha,
                                a,
                                rocblas_datatype_f16_r,
                                lda,
                                b,
                                rocblas_datatype_f16_r,
                                ldb,
                                &beta,
                                c,
                                rocblas_datatype_f16_r,
                                ldc,
                                c,
                                rocblas_datatype_f16_r,
                                ldc,
                                rocblas_datatype_f32_r,
                                rocblas_gemm_algo_standard,
                                0,
                                rocblas_gemm_flags_none));
}
